# HTTP Request Configuration
http:
  custProfile:
    request:
      host: "localhost"
      port: "8081"
      basePath: "/api"
      connectionIdleTimeout: "400000"
  custEmail:
    request:
      host: "localhost"
      port: "8081"
      basePath: "/api"
      connectionIdleTimeout: "400000"
# HTTP Listener Configuration
  host: "localhost"
  port: "8081"
  readTimeout: "300000"
# Email Configuration
email:
  smtp:
    host: "smtp.gmail.com"
    port: "587"
    password: "khpr ohrs nvfr wuew"
    starttls:
      required: "true"

# AMQP Configuration
amqp:
  connection:
    host: "fuji.lmq.cloudamqp.com"
    port: "5672"
    virtualHost: "zbdotnef"

# APIKit Configuration
apikit:
  api:
    location: "resource::25823cb5-4345-4fd0-8455-9b59e6259301:job-customer-notifications:1.0.0:raml:zip:job-customer-notifications.raml"
  outboundHeadersMapName: "outboundHeaders"
  httpStatusVarName: "httpStatus"